src/theme/variables.css

updated colors to match style guide

---

src/pages/Profile.css
src/pages/Profile.tsx

Created profile page with fixed values. Picture below:

Created base profile page

---

src/components/CustomList.tsx
src/pages/Home.css
src/pages/Home.tsx

Approve it for now so we can apply the CustomList component to our other pages. Remaining To-dos for me: Add '+' button, add images to the left of list items, add '>' icon on right of list items, collect values entered into searchbar, make searchbar not as ugly. Current image:

Created base home page

---

package-lock.json
package.json
src/App.tsx
src/components/BoardStack.tsx
src/components/CustomList.tsx
src/components/Logout.tsx
src/components/TabBar.tsx
src/pages/Board.tsx

- @sumiv i added href that links to the board view in the customlist component but can we think about how to do it dynamically?

added board view, added stack component, changed a link

---

src/App.tsx
src/components/CustomList.tsx
src/components/TabBar.tsx
src/pages/Organization.tsx

Created base Organization page

---

src/pages/LandingPage.css
src/pages/MyOrgs.tsx

For Sprint 2 Demo. Click "Add Organization" on My Orgs makes SyncSpace's Boards magically pop up

Added Org Creation with Button

---

src/pages/MyOrgs.css
src/pages/MyOrgs.tsx

+ Button
Popover
Currently takes users to specific organization page upon being clicked.

Added create new organization button

---

src/pages/Board.css
src/pages/MyOrgs.css
src/pages/MyOrgs.tsx
src/pages/Organization.tsx

It's ugly but it works. Will de-uglify later. Both redirect to Board page, will have to add AI creation flow.

Added create board/board with ai button

---

src/components/SpecificOrganization.tsx
src/pages/MyOrgs.tsx
src/pages/Organization.tsx
src/types.ts

Request for orgs data

---

capacitor.config.ts
src/App.tsx
src/components/SpecificOrganization.tsx
src/main.tsx
src/pages/MyOrgs.tsx
src/theme/variables.css
src/types.ts
tsconfig.json

Closes #67
- orgs should be working almost 100% now, you gotta make sure u have orgs but it shouldn't crash if u don't. lmk if it does
- still need to get creating orgs working
- still need to update the link to individual boards
- actually ^ need to redo router
- 
other than that it works!

67 finish my orgs

---

capacitor.config.ts
src/App.tsx
src/components/DeleteAccount.tsx
src/components/SpecificOrganization.tsx
src/main.tsx
src/pages/MyOrgs.tsx
src/pages/Profile.tsx
src/theme/variables.css
src/types.ts
tsconfig.json

Closes #70 
- user orgs show up in profile page
- delete account fully works now, alert also works so please be careful with your account lol
- member since will be added later, auth0 config has to change first

70 profile page improvements

---

src/components/SpecificOrganization.tsx

ok fully renders page but need to update customlist component

---

src/components/BoardStack.tsx
src/components/CardSettings.tsx
src/pages/Board.css

Things occurred. Card settings....?

Card Settings

---

.gitignore
src/components/BoardStack.tsx
src/components/CardSettings.tsx
src/components/SpecificOrgList.tsx
src/pages/Board.tsx
src/pages/Home.tsx
src/pages/MyOrgs.tsx
src/pages/OrgDetail.tsx
src/types.ts

Closes #62 
Closes #73 
Closes #63 
https://github.com/Sync-Space-49/syncspace-mobile/assets/72991783/26b09228-05f3-4f33-bba6-c663e7eedce3
- ooops didn't mean to do it in one commit but lmao
- boards, panels, stacks, and cards all render
- card settings updated to include card specific details
- updated types to more accurately describe types from db
- fixed ui issue with add button on myOrgs
- added some fucked up code that makes a new personal org for users on first login in Home page (it may or may not continue to make new orgs until they log out and log back in)
- tbh i don't remember what i made specificOrgList for but it was probably to try and fix one of the bugs 
https://github.com/Sync-Space-49/syncspace-mobile/assets/72991783/e669d7f4-6e37-417c-8efe-a03682857bf4
- plenty lmao
- …

added most of board functionality

---

src/components/BoardStack.tsx
src/components/NewStack.tsx
src/components/OrgList.tsx
src/components/StackSettings.tsx
src/pages/Board.css
src/pages/Board.tsx
src/types.ts

Closes #93 
Closes #94 
https://github.com/Sync-Space-49/syncspace-mobile/assets/72991783/bfaa0124-6535-48e1-afe8-7e999bee68f4
- added NewStack component that is placed at the end of all other stacks or as the only stack if no other stacks exist
- added StackSettings component that handles editing and deleting stacks
- commented out the .button css in board.css bc it was messing with the design of the stacks
- any stack updates (create,update, delete) does not automatically update the panel

93 create stack

---

src/components/SpecificOrganization.tsx
src/pages/MyOrgs.tsx
src/pages/OrgDetail.tsx

User is able to click + button on my orgs, have popover show, enter info, have org created with info entered, and have popover disappear. 
Problems: Showing up as undefined when redirected (history.push() line in CreateOrganizations is commented out for now).

Create Orgs Modal & Redirect attempt

---

src/components/CustomList.tsx
src/components/OrgList.tsx
src/components/SpecificOrgList.tsx
src/components/TabBar.tsx
src/pages/MyOrgs.tsx

Closes #107 
u saw it with ur eyes

fixed router lol

---

src/App.tsx
src/components/TabBar.tsx
src/pages/OrgDetail.tsx

You can generate a board with AI now and it works! yay

Added generate board functionality

---

src/components/BoardStack.tsx
src/components/CardSettings.tsx
src/components/CustomList.tsx
src/components/NewCard.tsx
src/components/NewPanel.tsx
src/components/NewStack.tsx
src/components/StackSettings.tsx
src/components/TabBar.tsx
src/pages/Board.tsx
src/pages/MyOrgs.tsx
src/pages/OrgDetail.tsx
src/pages/Profile.tsx
src/types.ts

Closes #101 
Closes #100 
https://github.com/Sync-Space-49/syncspace-mobile/assets/72991783/d8095049-09a4-4b9f-b304-c89c104c2464
_(haha low res video)_
- nearly every single line in board.tsx (sorry she got fat)
- honestly? it's 3 am idk what was changed. if something broke i'll fix it tm or thursday
- edit/delete board wasn't touched because the scope of this pr got wayyy too big
- um. i don't think boardstack is ussed anymore and some other files are also redundant.
basically. i am a man of my word and i said i would get this pr out if it was th last thing that kills me and i'm not dead yet.

100 edit delete cards

---

src/pages/Board.css
src/pages/Board.tsx
src/pages/OrgDetail.tsx
src/theme/variables.css
src/types.ts

Closes #91 
don't even ask idk

added delete board functionality, added edit board functionality

---

src/components/TabBar.tsx
src/pages/Home.tsx
src/pages/OrgDetail.tsx

What works: 
- displays recent boards, favorited boards, and my cards accurately as assigned to user
- recent boards and favorited boards take you to the right board page
- my cards does not take you to the right page as org and board is not stored on there
What to add: 
- limit recent boards to 3
- sort recent boards by last modified

Basic Home Page Created
